##########################################################################################
#                                                                                        #
#                       Pre-commit configuration file                                    #
#                                                                                        #
##########################################################################################
---
default_language_version:
    python: python3

repos:
    ####################################### Various Checks ###############################
    # Various checks
    -   repo: https://github.com/mmphego/pre-commit-hooks
        rev: master
        hooks:
            -   id: autopep8
            -   id: black
            -   id: flake8
            -   id: isort
            -   id: mypy
            -   id: prepend-jira-link
            -   id: proselint
            -   id: pydocstyle
            -   id: pytest
            -   id: python-check-mock-methods
            -   id: python-no-eval
            -   id: python-no-log-warn
            -   id: python-use-type-annotations
            -   id: shellcheck
            -   id: wily
            -   id: yamllint
