---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: shellcheck
  name: Test shell scripts with shellcheck
  description: Shell scripts conform to shellcheck
  entry: scripts/shellcheck.sh
  language: script
  types: [shell]
  # https://github.com/koalaman/shellcheck/wiki/SC1091
  args: [-e, SC1091]
  additional_dependencies: [shellcheck]
